async function deprecate (context, command) {
  const { github, payload } = context

  // We only target PRs
  if (!payload.issue.pull_request) return

  // 1. Extract necessary info
  const { owner, repo } = context.repo()
  const { number, body } = payload.issue

  // 3. Write deprecation notice
  github.issues.createComment({
    owner,
    repo,
    number,
    body: `
We've deprecated the \`/depends\` and \`/ensure\` commands in favor of the new single inline command: \`depend\` (no slash). The new command works similar to how you may [close issues using keywords](https://git.io/vNxHZ) on GitHub but **only** in pull request description.

The following keywords followed by an issue number, will mark that issue as dependency:

* depend on
* depends on
* depended on

**Examples**

You may write the end of PR description:

> Depends on #&#8203;1

or it can be anywhere:

> Do officia occaecat ad this **depends on #&#8203;1** magna aliquip aliquip labore adipisicing sint nostrud adipisicing sunt laboris exercitation. Oh, and it **depends on #&#8203;2** too.

All dependencies added using the old commands should have already been converted to the new syntax by for you. The old commands will just write comments similar to this one.

Sorry for any inconveniences!

-------

🤖 This comment was generated by [**DEP[bot]**](https://github.com/ahmed-taj/dep). Please report issues [here](https://github.com/ahmed-taj/dep/issues).

Happy coding!
  `
  })
}

module.exports = deprecate
