const notice = `
We've deprecated the \`/depends\` and \`/ensure\` commands in favor of the \
new single inline command: \`depend\` (no slash). The new command works \
similar to how you may [close issues using keywords][ref] on GitHub but \
**only** in pull request description.

The following keywords followed by an issue number, will mark that issue as \
dependency:

* depend on
* depends on
* depended on

**Examples**

You may write the end of PR description:

> Depends on #&#8203;1

or it can be anywhere:

> This pull request **depends on #&#8203;1** which does bla bla bla. Oh, and \
it **depends on #&#8203;2** too.

All dependencies added using the old commands should have already been \
converted to the new syntax for you. The old commands will just write \
comments similar to this one.

Sorry for any inconveniences!

-------

🤖 This comment was generated by [**DEP [bot]**][repo]. Please report issues \
[here][issues].

Happy coding!

[ref]: https://git.io/vNxHZ
[repo]: https://github.com/ahmed-taj/dep
[issues]: https://github.com/ahmed-taj/dep/issues
`

async function deprecate (context, command) {
  const { github, payload } = context

  // 1. We only target PRs
  if (!payload.issue.pull_request) return

  // 2. Extract necessary info
  const comment = context.issue({ body: notice })

  // 3. Write deprecation notice
  github.issues.createComment(comment)
}

module.exports = deprecate
